### ISSUE TITLE
Prueba de integracion continua en travis!

### ISSUE THREAD

**Issue by DiegoPv** [GabrielEValenzuela/AutmatedTellerMachineProject#1]
No paso la primera Prueba en travis! 
https://travis-ci.org/GabrielEValenzuela/AutmatedTellerMachineProject

**Comment by GabrielEValenzuela** [comment]
Debido a que no se utilizaba en ese entonces Gradle, y al ejecutar los JUnit 4.12, Travis no poseía las librerías. 
Al hacer el proyecto utilizando dicha herramienta, se logra solventar ese problema como otros, por ejemplo, la forma de distribución.
